dist: xenial
sudo: required
language: node_js #指定系统环境
node_js: #指定版本
  - 10
cache: npm # 缓存依赖
addons:
  ssh_known_hosts: $serverIP #指定远程服务器地址
# 全局参数定义
# env:
#   global:
#     - NODE_ENV="production"
install:
- npm install
before_script:
- npm run build:prod # 打包编译
script:
- npm run test #测试用例

