language: node_js #指定系统环境
node_js: 11 #指定版本
addons:
  ssh_known_hosts: $serverIP #指定远程服务器地址
install:
- npm install
before_script:
- npm run server:prod # 打包编译
script:
- npm run test #测试用例

# after_script:
#构建完毕，自动将代码分发到远程主机
# - scp -o StrictHostKeyChecking=no ./docs/ root@$ip2:/docs
before_install:
- openssl aes-256-cbc -K $encrypted_ee81ad9fc488_key -iv $encrypted_ee81ad9fc488_iv
  -in zzq_rsa.enc -out ~/.ssh/zzq_rsa -d
